### ISSUE TITLE
Faceted search

### ISSUE THREAD

**Issue by maehr** [Stadt-Geschichte-Basel/forschung.stadtgeschichtebasel.ch#1]
### Describe what feature you'd like. Pseudo-code, mockups, or screenshots of similar solutions are encouraged!

TBD

Furthermore

- 1 of 6 objects not H6
- remove title
- replace search field with search button

### What type of pull request would this be?

Enhancement

### Any links to similar examples or other references we should review?

See https://github.com/CollectionBuilder/collectionbuilder-csv/issues/79 for further reference

**Comment by koilebeit** [comment]
is covered in #167
