### ISSUE TITLE
Make tagging and collection page more consistent

### ISSUE THREAD

**Issue by maehr** [Stadt-Geschichte-Basel/forschung.stadtgeschichtebasel.ch#10]
### Describe what feature you'd like. Pseudo-code, mockups, or screenshots of similar solutions are encouraged!

Collection

- Full width?
- JPEG → Foto (JPEG,PNG...)
- Tagging more consistent

### What type of pull request would this be?

None

**Comment by maehr** [comment]
- [ ] Type (Compound et al) can be removed

**Comment by koilebeit** [comment]
is covered in #77
