### ISSUE TITLE
lunr search options do not work

### ISSUE THREAD

**Issue by koilebeit** [Stadt-Geschichte-Basel/forschung.stadtgeschichtebasel.ch#116]
### Current Behavior

lunr search options do not work, or only with the English field names.

### Steps To Reproduce

1. go to [https://forschung.stadtgeschichtebasel.ch/search/index.html](https://forschung.stadtgeschichtebasel.ch/search/index.html)
2. type in "datum:1577" -> no results
3. type in "date:1577" -> two results

### Anything else?

The translation for "Fuzzy match" is also still missing

**Comment by maehr** [comment]
@koilebeit the easiest fix is to adapt the translations/docs in {{ site.data.translations['_layouts']['search.html']['field-name'][site.lang] in <https://github.com/Stadt-Geschichte-Basel/forschung.stadtgeschichtebasel.ch/blob/main/_data/translations.yml>(referenced from <https://github.com/Stadt-Geschichte-Basel/forschung.stadtgeschichtebasel.ch/blob/main/_layouts/search.html>)

I encountered a bug while researching this: In <https://github.com/Stadt-Geschichte-Basel/forschung.stadtgeschichtebasel.ch/blob/main/_layouts/search.html> the fields do not get rendered.
```html
                            <ul>
                                <li>{{ site.data.translations['_layouts']['search.html']['field-name'][site.lang] | default: 'Search
                                    a specific field: use the field name, colon, then your query, e.g. <code>title:foo</code>,
                                    <code>date:1911</code>, <code>subject:tree</code>. In this collection you can use (( fields |
                                    join: ", " )).' }}</li>
```

You find my PR over here: https://github.com/Stadt-Geschichte-Basel/forschung.stadtgeschichtebasel.ch/pull/121
