### ISSUE TITLE
remove child objects from browse page

### ISSUE THREAD

**Issue by koilebeit** [Stadt-Geschichte-Basel/forschung.stadtgeschichtebasel.ch#117]
and remove object type button (eg "Compound Object")

**Comment by koilebeit** [comment]
If we remove the child objects from the browse page, they can no longer be searched for on the browse page (e.g. "Geodaten"). It still works in the search slot in the navigation.
@maehr @mtwente would that be ok for you, or should we ask cristina?

now:
![image](https://github.com/Stadt-Geschichte-Basel/forschung.stadtgeschichtebasel.ch/assets/73133626/5269ede7-f5d5-4b44-b97c-3ac79a53f4ef)

browse-child-objects: false:
![image](https://github.com/Stadt-Geschichte-Basel/forschung.stadtgeschichtebasel.ch/assets/73133626/6cc0f5ea-bdae-4487-91a5-c8bef429eb55)

search slot in the navigation:
![image](https://github.com/Stadt-Geschichte-Basel/forschung.stadtgeschichtebasel.ch/assets/73133626/cfce2cde-81a2-4dcf-981b-1463ad5b53dd)

**Comment by koilebeit** [comment]
.. and the child objects would no longer populate cloud and list pages like "Themen" in the event that they may have other/further subjects than the parent object

**Comment by maehr** [comment]
I would encourage users to use the general search. We might want to remove the filter field. What do you think?

**Comment by mtwente** [comment]
> I would encourage users to use the general search. We might want to remove the filter field. What do you think?

What I like about the filter feature is that you get a visual clue about the search result. With the general search, it's just the textual information. It's easier to skim the thumbnails for search results that might be of relevance than the results table of the general search box.

Also, if I use the general search, subject and era tags are non-clickable at the moment and do not stand out visually. When I search for something using the filter on the browse page, not only do I have the tags displayed prominently, but I can also just click to compile another subset of the collection.
To encourage users to use the general search would then steer them in another direction in terms of how they will be using the collection, in a less exploratory way (I think). Perhaps this is something for the survey?
