### ISSUE TITLE
Global Trigger Warning

### ISSUE THREAD

**Issue by maehr** [Stadt-Geschichte-Basel/forschung.stadtgeschichtebasel.ch#154]
### Describe what feature you'd like. Pseudo-code, mockups, or screenshots of similar solutions are encouraged!

The Digitalausschuss wants us to have a global trigger warning instead of conditional trigger warnings. The warning should cover the whole display. The trigger warning should only be displayed once per visitor (or visit, depending on the implementation with session cookie or local storage).

New wording, approved by Digitalausschuss

> Die historischen Materialien auf dieser Datenbank dokumentieren historische Vorgänge und Ereignisse. Sie werden unverändert präsentiert und sind primär für Forschungszwecke bestimmt. Als historische Quellen spiegeln sie Normen und Werte ihrer Zeit und können veraltete, vorurteilsbeladene oder diskriminierende Stereotypen enthalten. Solche zeitgenössischen Inhalte werden in der ursprünglichen Terminologie beibehalten, um die historische Authentizität der Quellen zu bewahren und eine transparente wissenschaftliche Aufarbeitung zu ermöglichen. Sie spiegeln in keiner Weise die Überzeugungen und Haltungen der Verantwortlichen dieser Datenbank. 

### What type of pull request would this be?

Enhancement

### Any links to similar examples or other references we should review?

- This feature obsoletes https://github.com/Stadt-Geschichte-Basel/forschung.stadtgeschichtebasel.ch/issues/136

**Comment by koilebeit** [comment]
solved by #155
