### ISSUE TITLE
Change Era Fields

### ISSUE THREAD

**Issue by mtwente** [Stadt-Geschichte-Basel/forschung.stadtgeschichtebasel.ch#156]
### Describe what feature you'd like. Pseudo-code, mockups, or screenshots of similar solutions are encouraged!

Change the [era field](https://forschung.stadtgeschichtebasel.ch/eras.html):

* add Frühe Neuzeit
* remove Zeitgeschichte and Neuzeit
  * replace with 19. Jahrhundert, 20. Jahrhundert, 21. Jahrhundert

### What type of pull request would this be?

Enhancement

**Comment by koilebeit** [comment]
Done
