### ISSUE TITLE
Fullscreen mode does not work on the page

### ISSUE THREAD

**Issue by maehr** [Stadt-Geschichte-Basel/forschung.stadtgeschichtebasel.ch#162]
### Current Behavior

On the page https://forschung.stadtgeschichtebasel.ch/items/abb14219.html#m14219, the fullscreen mode for images does not work as expected. After clicking on the fullscreen button, the image does not display, and instead, only a blocked icon appears (see attached screenshots). This issue occurs when trying to view the image of the "Bürgermeister der Stadt Basel, mit Oberstknecht und zwei Ratsdienern." 

**Steps to Reproduce**:  

**Expected behavior**:  
The image should display in fullscreen mode without any blocking or error.

**Actual behavior**:  
Instead of the image displaying, there is only a blocked icon (see attached screenshots).

**Screenshots**:  

- Screenshot 1: Normal image view before attempting fullscreen mode.  
  <img width="963" alt="Screenshot 2024-10-17 at 14 24 52" src="https://github.com/user-attachments/assets/211de327-2c9a-4ec9-baec-bcf82c339ca7">
- Screenshot 2: Blocked icon that appears when trying to enter fullscreen mode.
  <img width="1073" alt="Screenshot 2024-10-17 at 14 24 35" src="https://github.com/user-attachments/assets/b7fd9267-479d-4bc6-9178-08a362e08684">

### Steps To Reproduce

1. Navigate to https://forschung.stadtgeschichtebasel.ch/items/abb14219.html#m14219.
2. Click on the image to enlarge it.
3. Attempt to activate the fullscreen mode by clicking the fullscreen button.
4. Notice that the image does not display properly.

**Comment by koilebeit** [comment]
This happens with all TIFF-Objects.

> The Spotlight gallery library does not support TIFF files natively. According to discussions on the GitHub repository, it will only display TIFF files if the browser itself supports rendering TIFF images. This limitation is browser-dependent, and many modern browsers do not support TIFFs natively without plugins or special handling​
> [GitHub](https://github.com/nextapps-de/spotlight/issues/30)
> .
> 
> For PDF files, Spotlight provides an alternative approach by embedding them as <iframe> elements instead of directly handling the file​
> [GitHub](https://github.com/nextapps-de/spotlight/issues/30)
> . A similar workaround could be applied for TIFFs, such as converting them to more widely supported formats like JPEG or PNG before displaying them in the gallery.
> 
> If your project requires TIFF file handling, you might need to look into server-side conversion tools or using another library that specializes in TIFF file display.

**Comment by maehr** [comment]
@koilebeit Thank you for investigating this issue. I see a forth and even simpler solution: Use `image_thumb` instead of `object_location` for fullscreen. Otherwise your browser might try to load a 2GB tiff. OK with you?
