### ISSUE TITLE
🐛 Bug: Data Not Displayed for Transcription Records

### ISSUE THREAD

**Issue by maehr** [Stadt-Geschichte-Basel/forschung.stadtgeschichtebasel.ch#190]
#### Current Behavior:
When navigating to the page [Transkriptionen aus den Stammbüchern der niederländischen Kolonialarmee](https://forschung.stadtgeschichtebasel.ch/items/abb100359.html#m100359), the data for the transcription records is not displayed. Only metadata and buttons for actions (e.g., "Download CSV," "Fehlerhafte Metadaten melden") are visible, but no actual data is presented on the page.

<img width="1412" alt="Screenshot 2024-11-22 at 14 22 00" src="https://github.com/user-attachments/assets/78aed069-50ba-4499-b795-730db1b79d1e">

#### Expected Behavior:
The transcription data for the listed records should be displayed on the page, or the functionality to interact with and view the data (such as visualizing it in a timeline or downloading it) should be functional.

### Steps To Reproduce

1. Go to <https://forschung.stadtgeschichtebasel.ch/items/abb100359.html#m100359>
2. Observe that no transcription data is shown on the page.
3. Only metadata (e.g., title, description, identifier) and action buttons are visible.

**Comment by koilebeit** [comment]
This happens when the Omeka server is not working. Could be partly solved with #192
