### ISSUE TITLE
Extended time format

### ISSUE THREAD

**Issue by maehr** [Stadt-Geschichte-Basel/forschung.stadtgeschichtebasel.ch#4]
### Describe what feature you'd like. Pseudo-code, mockups, or screenshots of similar solutions are encouraged!

TBD

### What type of pull request would this be?

Enhancement

### Any links to similar examples or other references we should review?

See <https://github.com/CollectionBuilder/collectionbuilder-csv/issues/62> and <https://github.com/CollectionBuilder/collectionbuilder-csv/issues/43> for further reference

**Comment by koilebeit** [comment]
In my opinion, there are two possible implementation options without changing the visualization as a table:
1. each edtf-date in the data gets its own row:


![Image](https://github.com/Stadt-Geschichte-Basel/forschung.stadtgeschichtebasel.ch/assets/73133626/b7579686-82aa-490d-8673-bbd7cb9c5bf7)



2a. only years get a row and the items are assigned to the year occurring in the edtf format (e.g. 1925~ = 1925 or 19XX = 1900) and for periods assigned to each corresponding year (e.g. 1384/1390 = 1384 **and** 1390)
or
2b. only years get a line and the items are assigned to the year occurring in the edtf format (e.g. 1925~ = 1925 or 19XX = 1900) and for time periods only to the first corresponding year (e.g. 1384/1390 = 1384)


![Image](https://github.com/Stadt-Geschichte-Basel/forschung.stadtgeschichtebasel.ch/assets/73133626/eb8dfb57-c815-48cd-ac42-8d214aa62e7c)

I would prefer the second variant. @mtwente @maehr what do you think? or do you have other ideas?

**Comment by maehr** [comment]
I like the first variant. We should add some instructions on how to read EDTF

**Comment by maehr** [comment]
See also https://github.com/Stadt-Geschichte-Basel/forschung.stadtgeschichtebasel.ch/issues/30
