### ISSUE TITLE
Colors schema 

### ISSUE THREAD

**Issue by maehr** [Stadt-Geschichte-Basel/forschung.stadtgeschichtebasel.ch#43]
### Describe what feature you'd like. Pseudo-code, mockups, or screenshots of similar solutions are encouraged!

I'd like to have the same colors as on https://stadtgeschichtebasel.ch/

### What type of pull request would this be?

Enhancement

**Comment by maehr** [comment]
@mtwente How is your PR coming along? Will you be ready Monday around noon? If not I'll change `_data/config-theme-colors.csv`  to the following values as a temporary fix. Is this ok with you?

```csv
color_class,color
primary,#3A1E3E
secondary,
success,
info,#86BBD8
warning,#F6AE2D
danger,#F63E02
light,#F8F9FA
dark,#3A1E3E
```

**Comment by mtwente** [comment]
@maehr I'll get it done by tomorrow evening. And I've added updating the example screenshot on the portal to my to-do list as well.
