### ISSUE TITLE
Add compound_objects

### ISSUE THREAD

**Issue by koilebeit** [Stadt-Geschichte-Basel/forschung.stadtgeschichtebasel.ch#59]
There are two options for objects with multiple items: to mark them as "compound_objects" or as "multiple" in the metadata table. 
Depending on this, they are displayed differently on their item page. Here is an example with both versions:

[https://koilebeit.github.io/forschung.stadtgeschichtebasel.ch](https://koilebeit.github.io/forschung.stadtgeschichtebasel.ch)

Both are easy to implement. However, it is necessary that all items of an object have their own row in the metadata csv and have the parentID assigned to it. (see also:  [https://collectionbuilder.github.io/cb-docs/docs/metadata/compound-objects/#compound_object](https://collectionbuilder.github.io/cb-docs/docs/metadata/compound-objects/#compound_object))

In my opinion, "multiple" objects only make sense if all (sub-)items are images.
@maehr  @mtwente what do you think? Is a PR necessary for this?

**Comment by maehr** [comment]
Thank you very much for your work. I think we do not need a PR for that but we need to figure out how to implement this for the import script from Omeka after the book presentation. Multiple if its the same type and compound for mixed types makes sense.
