### ISSUE TITLE
Custom collection-banner

### ISSUE THREAD

**Issue by maehr** [Stadt-Geschichte-Basel/forschung.stadtgeschichtebasel.ch#66]
### Describe what feature you'd like. Pseudo-code, mockups, or screenshots of similar solutions are encouraged!

I want a custom `collection-banner.html` with logo and social links.

### What type of pull request would this be?

New Feature

**Comment by koilebeit** [comment]
In the new custom _includes/collection-banner-sgb.html target=_blank is missing on external links. See
https://github.com/Stadt-Geschichte-Basel/forschung.stadtgeschichtebasel.ch/blob/551d736c391c2e5da2932080dd853eef9f0c416b/_includes/collection-nav.html#L18-L22
and
https://github.com/Stadt-Geschichte-Basel/forschung.stadtgeschichtebasel.ch/blob/551d736c391c2e5da2932080dd853eef9f0c416b/_includes/collection-nav.html#L34-L38
